Jiwon's Feedback
ksmin23/analytics-on-aws pull request #1
Opened 2020-12-27 13:01 UTC by yjw113080

I focused on making this lab easier for those who are not too familiar with AWS services yet.
- I added bunch of deep links for Service consoles.
- I also attached a lot of screen shots and additional explanation.

However I've not made any major change such as dividing the whole contents into two/three parts, or using IAM Roles instead of IAM User credentials. I expect this can be happen next week.

2020-12-28 06:29 UTC, ksmin23 requested changes

2020-12-28 06:29 UTC, ksmin23 commented on content/lab-setup/iam-user/_index.ko.md
> +1. [이 링크](https://console.aws.amazon.com/iam/home#/users$new)를 클릭하여 IAM User 생성 콘솔로 이동합니다.
IAM User를 생성할 수 있는 링크를 알려주는 것도 좋은데, 바로 가기 링크만 알려주는 경우, AWS Console의 어떤 메뉴에 접속해서 IAM User를 생성하는지를 알수 없으므로, AWS Console에서 부터 IAM 서비스에 접속하는 단계는 그대로 남겨두고, `AWS Management Console` 이나 `IAM 서비스` 에 링크를 거는 것이 좋을 것 같습니다.

2020-12-28 06:29 UTC, ksmin23 commented on content/lab-setup/iam-user/_index.ko.md
> +  ![](/analytics-on-aws/images/iam-user.png)
`![](/analytics-on-aws/images/iam-user.png)` => `![iam-user](/analytics-on-aws/images/iam-user.png)` 식으로 변경해주세요.

2020-12-28 06:29 UTC, ksmin23 commented on content/lab-setup/ec2-user-configuration/_index.ko.md
> +1. [EC2 콘솔](https://us-west-2.console.aws.amazon.com/ec2/v2/home?region=us-west-2#Instances:)에서 방금 생성한 인스턴스를 선택하고 **Connect** 를 클릭합니다.
EC2 인스턴스에 접속하는 방법을 ssh와 connect를 이용하는 방법 2가지 모두를 설명해주면 좋을 것 같습니다.

2020-12-28 06:29 UTC, ksmin23 commented on content/build-analytics-system/kinesis-data-firehose/_index.ko.md
> +1. [이 링크](https://us-west-2.console.aws.amazon.com/firehose/home?region=us-west-2#/wizard/nameAndSource)를 클릭하여 새로운 Firehose 전송 스트림 생성을 시작합니다.
`[이 링크](https://us-west-2.console.aws.amazon.com/firehose/home?region=us-west-2#/wizard/nameAndSource)` 이런 식으로 링크를 거는 경우, 만약 ap-northeast-2 (서울 리전)에서 실습을 하는 경우에는 region을 변경해야하므로, 링크를 거는 것 보다는 AWS Console에서 어떤 경로로 메뉴에 접속할 수 있는지를 설명해주는 것이 좋을 것 같아서, 처음 부터 링크를 걸지 않았습니다.
이렇게 링크를 주는 경우, 실습 중에 리전이 변경되어서 Kinesis Data Stream은 서울 리전에 만들고, aws lambda는 버지니아 리전에 만들어서 자신이 생성한 서비스들을 못 찾는 분들도 간혹 있습니다.

2020-12-28 06:29 UTC, ksmin23 commented on content/build-analytics-system/kinesis-data-firehose/_index.ko.md
> +    S3 Error Prefix 를 다음과 같이 입력 합니다.
s3 error prefix를 입력하는 방식은 다양하게 변경할 수 있으므로, 이 실습에서는 `예를 들어서` 이렇게 prefix를 설정했다는 것이지, 반드시 이렇게 해야한다는 것은 아닙니다. 원래 문장이 좀더 좋을 것 같습니다.

2020-12-28 06:29 UTC, ksmin23 commented on content/build-analytics-system/kinesis-data-firehose/_index.ko.md
> +   1. S3 buffer conditions에서 Buffer size는 `1MB`, Buffer interval은 `60` seconds로 설정합니다.
번호를 `1.` => `(1)` 로 상위 번호와 구분되게 하면 좋을 것 같습니다.
이런 식으로.
```
6. (Step 4: Configure settings) 이 단계에서 아래와 같은 설정을 합니다.
(1) S3 buffer conditions에서 Buffer size는 `1MB`, Buffer interval은 `60` seconds로 설정합니다.
```

2020-12-28 06:29 UTC, ksmin23 commented on content/appendix/_index.ko.md
> +이에 필요한 `lambda-layer-resources-USERNAME`라는 이름의 s3 bucket을 생성합니다. USERNAME을 사용자의 ID로 대체하십시오.
`USERNAME` 대신 `xxxxxxxx` 로 변경하고, ``` `xxxxxxxx` 는 s3 bucket 이름이 겹치지 않도록 임의의 숫자나 문자를 입력 합니다.``` 라는 식으로 하면 변경하면 좋을 것 같습니다. 

예를 들어,

```
`lambda-layer-resources-xxxxxxxx`라는 이름의 s3 bucket을 생성합니다. `xxxxxxxx` 는 s3 bucket 이름이 겹치지 않도록 임의의 숫자나 문자를 입력 합니다.``` 라는 식으로 하면 변경합니다.
```

2020-12-28 06:29 UTC, ksmin23 commented on content/appendix/_index.ko.md
> -    ```shell script
shell script를 넣는 것 보다, `3-8. AWS Lambda` 에서 처럼, `AWS Lambda Layer에 등록할 Python 패키지 생성 예제` 링크를 추가해주는 것이 좋을 것 같습니다. 이렇게 하면, Python 패키지 생성 방법이 변경될 경우, 한 곳만 수정하면 되니까요.

2020-12-28 06:29 UTC, ksmin23 commented on content/appendix/_index.ko.md
> +1. ES 도메인을 최초 생성하는 경우, [Service Linked Role](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/slr-es.html) 을 생성해주어야 합니다. 아래 명령어를 수행하여 생성하십시오.
`AWSServiceRoleForAmazonElasticsearchService` 을 생성하지 않은 경우에 어떤 에러가 발생하나요? 혹시 에러나 warning관련 데이터도 있으면 추가해주면 좋을 것 같아서요.

2020-12-28 06:29 UTC, ksmin23 commented on content/appendix/_index.ko.md
> +    git clone https://github.com/ksmin23/aws-analytics-immersion-day.git
`$` 를 붙이지 않으면, terminal에서 shell script 전체를 copy에서 붙여넣기 하는 분들이 있습니다. 
그리고, `--profile cdk_user` 옵션을 사용한 이유는 aws configure로 설정한 사용자 계정이 여러개일 때, cdk_user가 default가 아니라면, 동작하지 않을 수 있으므로, 명시적으로 `--profile cdk_user` 를 주고 실행한 것 입니다.

2020-12-28 06:29 UTC, ksmin23 commented on content/lab-setup/ec2-user-configuration/_index.ko.md
> -    ```
shell script 전체를 복사해서 붙이는 것을 막고, 어떤 순서로 실행하는지 알려줄려고 단계를 나눈 것 입니다.

2020-12-28 13:30 UTC, yjw113080 commented on content/build-analytics-system/kinesis-data-firehose/_index.ko.md
> +1. [이 링크](https://us-west-2.console.aws.amazon.com/firehose/home?region=us-west-2#/wizard/nameAndSource)를 클릭하여 새로운 Firehose 전송 스트림 생성을 시작합니다.
링크에 리전이 들어가지 않도록 수정하겠습니다.

2020-12-28 13:53 UTC, yjw113080 commented on content/build-analytics-system/kinesis-data-firehose/_index.ko.md
> +    S3 Error Prefix 를 다음과 같이 입력 합니다.
평소에는 당연히 그런데, 워크샵 사용자 입장에서는 명확한 가이드를 받고 정확히 수행하며 학습하고자 하는 게 목표인 만큼 조금 더 확실하게 표현해줘야 한다고 생각했습니다. 아래와 같이 바꿔보면 어떨까요?
```
S3 Error Prefix 를 다음과 같이 입력 합니다. (참고: 실제 프로덕션 워크로드에서 사용할 때에는 다른 Error Prefix를 사용할 수도 있습니다.)
```

2020-12-28 13:58 UTC, yjw113080 commented on content/lab-setup/iam-user/_index.ko.md
> +1. [이 링크](https://console.aws.amazon.com/iam/home#/users$new)를 클릭하여 IAM User 생성 콘솔로 이동합니다.
@ksmin23 제 생각에 이 실습을 하는 사용자들은 콘솔에서 각 메뉴가 어디에 위치해있는지 보다는, 원하는 워크로드를 만드는 법을 배우고 싶은 분들일 것으로 생각합니다. 잘못된 링크로 들어가거나 헤매거나 해서 실습에 진행에 지장이 발생하는 것보다는 정확한 링크로 확실히 가이드를 주는 게 좋지 않을까요? 제가 실습하면서 약간 불편했어서 수정을 해봤습니다. 아래 다른 코멘트 달아주신 것처럼 리전 값만 제거하면 링크가 더 편리할 것 같은데 어떻게 생각하세요?

2020-12-31 00:06 UTC, ksmin23 commented on content/build-analytics-system/kinesis-data-firehose/_index.ko.md
> +    S3 Error Prefix 를 다음과 같이 입력 합니다.
네, 더 좋은 것 같습니다.

2020-12-31 00:13 UTC, ksmin23 commented on content/lab-setup/iam-user/_index.ko.md
> +1. [이 링크](https://console.aws.amazon.com/iam/home#/users$new)를 클릭하여 IAM User 생성 콘솔로 이동합니다.
region 값이 url에 들어가지 않으면, 괜찮을 것 같습니다. 바로 가기 링크를 따로 넣으면 어떨까 하는 생각도 듭니다.

2021-01-03 11:47 UTC, yjw113080 commented
성민님,
피드백 주신 내용 모두 반영하였습니다.
여기에 대해 IAM User configuration 부분을 빼고 IAM Role 을 사용하도록 수정한 부분이 추가되었습니다.
이에 따라 IAM User 생성 페이지가 삭제(전체 주석)되었고, EC2 설정 부분에 Modify IAM Role 내용을 추가하였습니다.

2021-01-14 03:47 UTC, merged